# JDBC for MySQL
spring.datasource.url=${TEST_DB_URL}
spring.datasource.username=${TEST_DB_USER}
spring.datasource.password=${TEST_DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# JWT
jwt.secret=${TEST_JWT_SECRET}
jwt.expiration=172800000

# Logging
#logging.level.org.springframework.security=DEBUG
logging.level.root=INFO

## frontend url 
#frontend.url=http://localhost:5173
