# JDBC for MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortnerdb
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=172800000

# Logging
#logging.level.org.springframework.security=DEBUG
#logging.level.org.url.shortner=DEBUG
#logging.level.root=DEBUG

